### PR TITLE
Code refactor | More types | Functional style 

### PR DESCRIPTION
**Pull request by Lenivaya**
# Changes

## Definitely typed custom provider for Store

Reading code I have noticed that you&rsquo;re using Provider for store without giving it any types

```js
// TODO
const Provider: any = RealProvider
```

and also that there&rsquo;s a lot of a store imports directly from the file where it was created, like this

```js
import store from "./store/main"
```

To get rid of those pattern and define proper types I created custom provider &#x2014; StoreProvider, which type definitions looks like that

```js
const StoreContext = createContext<Store>();

export type StoreComponent = FC<{
  store: Store;
  children: ReactNode;
}>;

export const StoreProvider: StoreComponent = ({
  store,
  children,
}): ReactElement => {
  return (
    <StoreContext.Provider value={store}>
      {children}
    </StoreContext.Provider>
  );
};
```

Function and types definitions shows us that StoreProvider will accept Store and pass it down all over the components tree via context. This fact give us another great possibility &#x2014; create usable helpers:

-   useStore hook
-   withStore HOC

In future that will also help us to properly test components by mocking the store passed to them.

### useStore hook

```js
export const useStore = (): Store =>
  useContext(StoreContext);
```

useStore hook give us ability to get store from any functional component just by writing that lines

```js
const store = useStore()
```

### withStore HOC

```js
export const withStore =
  (Component) => (props) => {
    return <Component {...props} store={useStore()} />;
  };
```

withStore is a High-Order Component which can wrap both, class and functional components passing store to them

can be used like this to pass store to a Component

```js
const Component = ({ store }) => {
    // some component logic
}

export default withStore(Component)
```

## Rewrite components in functional style, give them typings

As previously code was written in OOP style, it created a lot of problems. First and foremost, React with classes requires us to write much more boilerplate code. Components are begin to become just unreadable with all these

```js
this.props.store.diagram.engine.model.setLocked
```

Also I noticed something about a lot of just unused code, code that repeats over and over along components, like showSuccessToast. I commented out it untill better times and decided to rewrite all code with functional style, using hooks.

To give some view on how simple and obvious can be functional components let&rsquo;s look on the WorkbenchControl rewritten with functional style

```js
import React, { FC } from 'react';
import { observer } from 'mobx-react';
import BaseControl, {
  BaseControlStyle,
} from './BaseControl';
import { Store } from '../../store';

interface Props {
  store: Store;
}

const WorkbenchControl: FC<Props> = ({ store }) => {
  const [title, icon, page] = [
    'Story workbench',
    'fas fa-project-diagram',
    'Workbench',
  ];

  const style =
    page == store.metadata.page
      ? BaseControlStyle + ' text-malibu-600'
      : BaseControlStyle;

  const onClick = () => {
    store.setPage(page);
  };

  return (
    <BaseControl
      title={title}
      icon={icon}
      onClick={onClick}
      style={style}
    />
  );
};

export default observer(WorkbenchControl);
```

All whats happening is pretty clear and understandable. Function that represents BaseControl is also can be understood by simply looking the code

```js
import React, { FC } from 'react';

interface Props {
  id?: string;
  title: string;
  icon: string;
  onClick?: () => void;
  style?: string;
}

export const BaseControlStyle =
  'ml-4 text-gray-200 hover:text-malibu-500';

const BaseOnClick = () => {
  alert('Not implemented');
};

const BaseControl: FC<Props> = ({
  id = null,
  title,
  icon,
  onClick = BaseOnClick,
  style = BaseControlStyle,
}) => {
  return (
    <span
      id={id ?? title}
      title={title}
      className={style}
      onClick={onClick}
    >
      <i className={icon}></i>
    </span>
  );
};

export default BaseControl;
```

## Misc

When rewriting I also noticed a couple of things that is fixed now, or I have some thoughts about

### Keybindings

You forgot about importing Mousetrap library in App.tsx, by fixing this, keybindings like

-   shift + d (to open workbench)
-   shift + t (to open inspector)
-   shift + l (to open logs)

are working now

### Showing toasts

There was something about 3-5 components that used something like &ldquo;showSuccessToast&rdquo; or &ldquo;showFailedToast&rdquo;, in their declaration. I don&rsquo;t delete them, but good choice is to write some reusable function or component to show them, and delete all these repeated code. Signature for reusable showToast may look like this

```js
interface Props {
    message: string,
    success: boolean
}

const showToast(
    message,
    success,
    importance = notification,
) {
    // logic
}
```

***Will take care of this***

### Large components

There&rsquo;s a lot of monstrously large components. They all are using strange OOP pattern to declare things like headings or things that can be moved to their own components as related functions and then calling them in render, here&rsquo;s example

```js
      <div
        className={'flex font-mono text-xxs text-gray-200'}
        onDoubleClick={this.open.bind(this)}
      >
        <div className="flex-grow-0 max-w-md">
          {this.renderHeading()}
          {this.renderInPorts()}
          {this.renderOutPorts()}
          <div className="w-32">
            {/* Enforce min width with this div*/}
          </div>
        </div>

        {this.renderModal()}
      </div>
```

Instead of that approach we must separate components as much as possible. For these example it would be better to create directory sturctures with such files

```shell
ComponentName/
ComponentName/ComponentName.tsx
ComponentName/ComponentNameHeading.tsx
ComponentName/ComponentNameInPorts.tsx
ComponentName/ComponentNameOutPorts.tsx
```

That will help us in testing and better understanding of what we writing

***Will take care of this***

### CODE REVIEW

**Comment by Lenivaya** [comment]
Though it wasn't the purpose it seems like the number of unfixable errors reported by eslint reduced from 300 to 17

**Comment by Lenivaya** [comment]
Problem with running stories fixed

**Comment by ajthinking** [comment]
### Refactor
Thank you so much for this. Quality is way much better 🏆 

* When to reach for `const store = useStore()` VS `withStore(...`?

I'll need to practice the patterns a bit so might shoot questions later.

### Shortcuts
* Nice catch on the 'page' navigations.
* When adding a Node I usually do ALT+PLUS, start typing and then tab to the one I want then press _ENTER_. **It seems we lost the enter here.** (mouse double clicking it works fine). Btw, are you on a windows machine and do you think this approach will work OS independent as long as we use common keys like ALT?
* Later down the line we might want a configuration section where these are listed and potentially editable.

### How find errors when code is minified?
Let's say I found a bug. Check console where it ocured. Sees minified code, don't know where to do the fix in source. What is your workflow for this?

### Showing toasts
I was not sure about how to do the toasts 'system' so putting some general thoughts here that might be useuful if you continue improve it later on. In broader terms we need to
* give critical information like failed booting
* let the user see the workflow is running
* let the user see the workflow has completed running (success/fail)
* let the user see the workflow has completed running and has produced outputs (inspectables, downloads, feature counts etc)
* let the user see if there was a javascript error
* etc

Some of these might be suitable as a toast, other might be accomplished by other things like css highlighting/dimming etc...

### Large components
This is gonna be such a relief! Nice approach

**Review by ajthinking — APPROVED** [review]

**Comment by ajthinking** [comment]
> Problem with running stories fixed
> 

Your screenshot is missing this link:
image
But it works fine when I pull it so assume it was fixed since 👍

**Comment by Lenivaya** [comment]
> ### Refactor
> Thank you so much for this. Quality is way much better 
> 
> * When to reach for `const store = useStore()` VS `withStore(...`?
> 
> I'll need to practice the patterns a bit so might shoot questions later.
> 
- **useStore()** will be mainly used in components which hold state and pass it down with props, so if store is updated children&rsquo;s are updated too. Writing useStore() in every component is just pointless and will be really a bad pattern, so you need to correctly determine which component should hold the common state. Can be used only with functional components

 - **withStore()** can be used on (functional|class)components which must have store but doesn&rsquo;t get it from props, for example NodeWidget component requires store to be passed in it. But NodeModelFactory which renders NodeWidget can&rsquo;t normally have a store to pass, so we will wrap NodeWidget with our HOC like here

```js
export default withStore(NodeWidget)
```

and then easily use store in our component

```js

const NodeWidget = ({ _, _, store }) => {
  //
}
```


> * When adding a Node I usually do ALT+PLUS, start typing and then tab to the one I want then press _ENTER_. **It seems we lost the enter here.** (mouse double clicking it works fine). Btw, are you on a windows machine and do you think this approach will work OS independent as long as we use common keys like ALT?

Well I can&rsquo;t reproduce needed behavior even by checking out to the old commit (about 5 days ago). Neither *alt + enter* nor just *enter* works for me (Tested on linux). Even more it seems like it worked for you before just because there were no types. That binding was using *handleSelect* which is meant to be used for *onDoubleClick*, so handleSelect will get an event as an argument. But mousetrap don&rsquo;t pass any events to handleSelect, so it won&rsquo;t work properly. Will take closer look on how to make it work later

> ### How find errors when code is minified?
> Let's say I found a bug. Check console where it ocured. Sees minified code, don't know where to do the fix in source. What is your workflow for this?

Can agree that minified code interferes from findings bugs. I think in the mix config we must add conditions check&rsquo;s on what environment we want to bundle our code, whether it development or production and based on this enable/disable terser.

**Comment by ajthinking** [comment]
> useStore / withStore

Ok, got it! Saw the added trello cards on the other two questions, perfect 👍

**Pull request merged**
