### PR TITLE
Dynamic ports wip

### PR DESCRIPTION
**Pull request by ajthinking**
### Background
Sometimes we want the user to define the output ports. To test this out we can use the Filter node in [core/53](https://github.com/data-story-org/core/pull/53). This node should  accept an object and depending on value in attribute features will flow out through respective ports. It also needs an "unfiltered" port to output features that did not match any user provided ports.

image

### Suggested implementation so far
* As providing custom ports is kind of an a repeated action we should be able to hook this into repeatables.
* There is an old solution for that, needs to be removed
* Added an experiment `updaterepeatablePorts` in the node widget modal which could be used to "listen" to a ports column in a repeatable. Those values can be extracted and used to create ports (not working yet)
* NodeWidgetOutPorts does not react to props change so no new ports is added when typing in the ports list. Tried using with useEffect() but no success

### Repeatable sidenotes
* It does not work to put a select in a repeatable
* Confusion regarding what `options` in String_ (and other fields) refer to. Logging `options.name` will show the component is rendered not only for string fields but also for repeatables and potentially other non-string fields as well.
* Discovered that when attempting to fetch placeholder option: `placeholder={options.placeholder ?? 'hehehehe'}`. Seems it is not persisted but have a bit of a  hard time tracking the trace

### CODE REVIEW

**Comment by Lenivaya** [comment]
# Changes
## Automatic output ports creations
It's possible to configure output ports, for now ports creation only done when submitting(values in fields are still being automatically persisted so can't be lost). For this to work we must add asPort to our NodeParameter when defining node in the core package.
## UI
image
Screenshot 2021-08-08 at 22-03-22 DataStory

**Comment by ajthinking** [comment]
Making great headway!

Neat isPort approach. What do you think about even upgrading that to its own type `Port` alongside String_ and the others?

**Comment by Lenivaya** [comment]
> What do you think about even upgrading that to its own type `Port` alongside String_ and the others?

Think it's a great idea, we can strictly type that our Port can only be used on a simple fields like Strings, Numbers, Selects etc, and be sure that we can without errors handle each dynamic port creation. Will take care of this.

**Comment by Lenivaya** [comment]
# Updates
Changes for handling of the new Port field type
# GUI
Works as expected
image

**Comment by Lenivaya** [comment]
# Updates

Before, all dynamically configured ports were re-created during submission. That caused behavior when all links created with that ports were deleted every time modal submitted, which isn&rsquo;t great experience for the end user. So now, instead of deleting and re-creating dynamic ports with the new values, we&rsquo;ll instead remove only those modified in the modal.


# Example

Let&rsquo;s consider such diagram. We have two dynamically created ports and linked inspectors to them.

Screenshot 2021-08-13 at 15-02-43 DataStory


With the previous implementation, if one of the ports is being updated or deleted, all links from all dynamic ports automatically disappear. But with the new implementation, if we for example decide to delete first output port, it&rsquo;ll delete only and only it, unlinkng from it&rsquo;s inspector.

Screenshot 2021-08-13 at 15-03-02 DataStory


I see it much seamless experience for the end user as it was before.

**Comment by ajthinking** [comment]
> I see it much seamless experience for the end user as it was before.

Big improvement! Works great mostly, in some cases though I can create some strange behavior:

filter_bug_demo

**Comment by Lenivaya** [comment]
@ajthinking, try now, works like a charm for me

**Comment by ajthinking** [comment]
debug2

After renaming port2 to port2xxx
* port1 & Unfiltered untouched as expected
* port3 loosed its connection to inspector-port3 (!)
* port2xxx overtook connection to inspector-port3 (!)

Minor changes that would be nice
* Keep order of ports after edit
* Add a diagram.refresh somewhere so we don't have to touch/drag the diagram to see the result after edit

**Comment by Lenivaya** [comment]
> automatic refresh

Added

> p3 loosed its connection to inspector-p3 (!)
> p2xxx overtook connection to inspector-p3 (!)

Pretty strange that the roots of that problem comes from useHotkeys hook usage, so as temp workaround enter submission is disabled for the modals with dynamic ports(will work outside of input fields). Works as expected for me now

Screenshot 2021-08-14 at 22-35-25 DataStory

> Keep order of ports after edit

Since I haven't found any methods for in-place ports modification/renaming in diagrams library, and doing that things directly, by hand just causes a lot of errors. Implementation of something like the right order will require extra state and rearranges.

**Comment by ajthinking** [comment]
Works for me as well, nice job! Merge at will. Things we can fix as follow ups 👇  

<hr>

> temp workaround enter submission is disabled  

Previously I could tab to the plus sign and press ENTER ta add row, now this closes the modal?

<hr> 
It fails if no port was added. 

image

<hr>

Support dot notated path (or empty if primitive (non-objec) features). This is implemented in a few other nodes.
image

<hr>

> Keep order of ports after edit

Good call not really needed now

**Comment by Lenivaya** [comment]
> It fails if no port was added. 

fixed in data-story-org/core#53

> Support dot notated path

added in data-story-org/core#53

> Previously I could tab to the plus sign and press ENTER ta add row, now this closes the modal?

Yes but only for modals with ports parameters, unless I find why useHotkeys causes that issue

**Comment by Lenivaya** [comment]
> or empty if primitive (non-objec) features

addes in data-story-org/core#53

**Pull request merged**
