### PR TITLE
Allow opening NodeModal by request multiple times

### PR DESCRIPTION
**Pull request by Lenivaya**
# Background
Because of NodeWidgetHeader which gets broken by observer HOC, we can't really get reactive changes of store in our NodeWidget component. That's causes problem in opening NodeModal since handleModalRequest depends on store and must react as fast as possible. 
## Solution
To solve that issue I decided to extract all handling modal request logic into separate component wrapped by observer, and... It works pefect! Now you can without noticable problems use <kbd>enter</kbd> to open / reopen modals as many times as needed.

### CODE REVIEW

**Comment by Lenivaya** [comment]
@ajthinking

**Comment by ajthinking** [comment]
Upon entering the node I get this:
image

**Comment by Lenivaya** [comment]
> Upon entering the node I get this:


Can't reproduce in any way, tried entering text, reopening couple of times but no errors

**Comment by ajthinking** [comment]
Now even I cant reproduce it so probably because im on a bad connection and yarn or cache or something..
Neat solution!

**Comment by Lenivaya** [comment]
Seems like problem may be becase of calling setState inside of render function so fix won't be problematic.

**Comment by ajthinking** [comment]
Thought it dissaperd but still has it. Just deleted that comment

**Comment by ajthinking** [comment]
Thought it dissaperd but still has it. Just deleted that comment

**Pull request merged**
