### PR TITLE
Hotkey to open modal of newly created node

### PR DESCRIPTION
**Pull request by ajthinking**
### Background
We don't want to rely on mouse to open node modals. Typically after using SHIFT+PLUS we _directly_ want to open the modal to configure it.

### Implementation
* When a node is added to the diagram we clear any previous selection and selects the node instead.
* App listens for SHIFT+E and if a node is selected it sends a request to the store: `store.openNodeModal(node.id)`
* Store has a key `metadata.requestOpenNodeModal`
* The NodeWidgets listens to this key to see if it was their ID that was requested to open. If so opens it and resets the openRequest.

### Example
Now we don't have to reach for mouse when creating, configuring and exiting node modal like so:

* SHIFT+PLUS
* CreateJS...
* ENTER
* SHIFT+E
* TAB/EDIT FIELDS
* SHIFT+ENTER
* ...

### Improvements
* Ideally I think a user would like to enter a node with simply the ENTER key. However both ENTER and SHIFT+ENTER interferes with the current solution of quick save&exit in modals. @Lenivaya can you figure out a good solution for this? I also noticed in there we don't use `useHotKeys` any specific reason for that?
* Also please provide any feedback on the functional programming as Im new to this approach :stuck_out_tongue:

### CODE REVIEW

**Review by Lenivaya — APPROVED** [review]

**Comment by Lenivaya** [comment]
> I also noticed in there we don't use `useHotKeys` any specific reason for that?

It seems to me that useHotkeys is too much for simple things that can be done by standart library like form submitting by enter, I'd prefer using it for complex hotkeys starting from two keys combinations.  

> Ideally I think a user would like to enter a node with simply the ENTER key. However both ENTER and SHIFT+ENTER interferes with the current solution of quick save&exit in modals.

Can't see where it interferes with save&exit, NodeWidgetModal starts to listen to Enter keypress event when modal is open and removes listener on it's close so you can without problems use Enter keybinding to open specific modal in App component. 

One upgrade i see is adding submit and semi-submit for NodeWidgetModal, something like <kbd>Enter</kbd> for submit and close, and <kbd>shift</kbd> + <kbd>Enter</kbd> to just submit changes, or in the different order. Will take care of that.

**Comment by ajthinking** [comment]
> I'd prefer using it for complex hotkeys

makes sense 👍 

> Can't see where it interferes with save&exit

Ok, then maybe something else, though it feels suspect because it flashes open then flash closed and closeModal is triggered

**Comment by Lenivaya** [comment]
> Ok, then maybe something else, though it feels suspect because it flashes open then flash closed and closeModal is triggered

Try to use [e.stopPropagation()](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) in NodeWidgetModal submit handler, must prevent propagation of the Enter keypress event in the Parent components, so you can use Enter for both App and NodeWidgetModal

**Comment by ajthinking** [comment]
> Try to use e.stopPropagation() in NodeWidgetModal submit handler, must prevent propagation of the Enter keypress event in the Parent components, so you can use Enter for both App and NodeWidgetModal

I think it is the other way around App 'enter' is leaking into `NodeWidget`

**Comment by Lenivaya** [comment]
> I think it is the other way around App 'enter' is leaking into `NodeWidget`
Ok, let's merge this PR as a starting point, and I'll take a closer look on that problem later

**Comment by ajthinking** [comment]
Thanks!

**Pull request merged**
