### PR TITLE
Hotkeys

### PR DESCRIPTION
**Pull request by Lenivaya**
# Upgrade
- Enter now works in both App and NodeWidgetModal
- NodeWidgetModal now supports real-time persisting of input, try to open node modal and changing it's name, you'll see how header changes when you type. So even if user forgots to save and accidentaly clicks outside of a modal, all things he typed won't be deleted.

### CODE REVIEW

**Review by ajthinking — APPROVED** [review]
Awesome 👍 : Testing on Mac and Windows machines in a bit

**Comment by ajthinking** [comment]
* The autosave certainly make it easier. Don't think there is a great need to cancel and discard changes anyways.
* This renders the cancel and save buttons useless? Replace it with a "close" or "ok" instead?
* 
* I cant use enter/shift-enter within modal. Can you describe the intention in readme.md hotkeys table?
* Reproduce:
* Add CreateJSON
* Enter it
* Press ENTER - nothing happens
* Press SHIFT+ENTER - nothing happens
* Do the same standing in INPUT or TEXTAREA - nothing happens

If I understand intention and its only on mac I can take a closer look later

**Comment by ajthinking** [comment]
> For now automatic persisting saves just for the local state, so if you don't press save the parameters won't be saved in the global state.

It seems I can do the following
* Add a Create node
* Type in a field
* Sees emidiate change in node header if name field is edited
* Escape
* Reopen node
* Sees changes even though it should have only been saved to local state?

**Comment by Lenivaya** [comment]
> > For now automatic persisting saves just for the local state, so if you don't press save the parameters won't be saved in the global state.
> 
> It seems I can do the following
> 
> * Add a Create node
> * Type in a field
> * Sees emidiate change in node header if name field is edited
> * Escape
> * Reopen node
> * Sees changes even though it should have only been saved to local state?
> * Changes are also immidiately reflected in DiagramJSON tab

In in NodeWidget for open and close handlers we're using 
```js
store.diagram.engine.setLocked(true || false)
```
So changes are really not saved before you pressed save button

**Comment by ajthinking** [comment]
I did not press save and it still persist between different openings of the modal and it is also updated in the DiagramJSON.

**Pull request merged**
