### PR TITLE
Import headless diagrams

### PR DESCRIPTION
**Pull request by ajthinking**
Adds a store method `importDemo` to render a headless demo diagram. Needs [core/104](https://github.com/data-story-org/core/pull/104)

### Why
This is useful to let us create demos programatically as headless diagrams and then present them in the gui anyways. Doing it this way the demos need not be commited as json-blobs (serialized diagrams) but lets us use more manageable `DiagramBuilders` instead.

### New Splash page:
Demos can now be accessed by clicking the cards under home/'DataStory':

image.

### Notes / follow ups
* The `importDemo` method currently only support basic left-to-right diagrams
* existing Open functionality and demos differ in that when _opening_ we accept a serialized diagram with positions, while the _demos_ are positionless instances of `core/Diagram`, hence they can not use the same initializers...
* Further on we  can use the splash page to add links, help sections, news or whatever we need.
* The splash page could be set to opened by default at least for new users in github pages or other demos
* Needs improved styling of the splash page and cards

### CODE REVIEW

**Review by Lenivaya — APPROVED** [review]
Nice work! Love how that style of the splash screen with calmly dimmed colors feels, minimalism without unnecessary distractions

**Comment by ajthinking** [comment]
> Nice work! Love how that style of the splash screen with calmly dimmed colors feels, minimalism without unnecessary distractions

Haha thanks design not really my cup of tea 😅

**Comment by ajthinking** [comment]
@Lenivaya, seems something broke the pipe with this, can you see what I did wrong? https://github.com/data-story-org/gui/runs/3644626760

**Comment by Lenivaya** [comment]
> @Lenivaya, seems something broke the pipe with this, can you see what I did wrong? https://github.com/data-story-org/gui/runs/3644626760

It's time to release new version of core to package registry with latest changes, will do that now

**Pull request merged**
