### PR TITLE
Hotkeys fixes

### PR DESCRIPTION
**Pull request by Lenivaya**
# Info
- for modal it's now possible to submit using enter directly from input field, of course if it's not a textarea field
- shift + enter is removed as unneded because of auto persisting 
- [this error](https://user-images.githubusercontent.com/3457668/127986751-46993aec-fd93-4d9f-a7dd-73b08d91f67c.png) must be fixed now

### CODE REVIEW

**Comment by ajthinking** [comment]
Now it works for me as well aside from that bug.

Can you confirm this in practice means now there is no local/global state it is all the same?

**Review by ajthinking — APPROVED** [review]

**Comment by Lenivaya** [comment]
>  aside from that bug.

Can you send screenshot of the error? It defiitely must be fixed
> Can you confirm this in practice means now there is no local/global state it is all the same?

Data is persisted globally but it's always better to submit via enter/save, because of possible bugs that may be caused by locked engine model

**Comment by ajthinking** [comment]
Noticed the error only occures once. After error occured, closing and reopening node does not trigger it, nor adding a second node and entering that.
image

> Data is persisted globally but it's always better to submit via enter/save, because of possible bugs that may be caused by locked engine model

OK

**Comment by Lenivaya** [comment]
@ajthinking that works as fine as before for me, try to check if you still getting this error

**Comment by ajthinking** [comment]
Selected nodes Modal is not opened att ENTER now (so no error)

**Comment by Lenivaya** [comment]
Try doing hard refresh with Ctrl + f5

**Comment by ajthinking** [comment]
Did that, reinstall yarn modules, rerun yarn watch. Test in chrome and safari - both of them are listening to ENTER on seleceted node but after that nothing happens

**Comment by Lenivaya** [comment]
https://lenivaya.github.io/gui/ try on github pages

**Comment by ajthinking** [comment]
github pages works

**Comment by ajthinking** [comment]
When pulling master enter seems to work but still get the error

**Comment by Lenivaya** [comment]
> When pulling master enter seems to work but still get the error

Really can't reproduce this in any way, tried in a couple of browsers: 
- chrome
- firefox
- brave

but all works and I can't see any errors in the console. I tried even on my phone but nothing alike errors you have

**Comment by ajthinking** [comment]
Very strange :sweat_smile:, Ill try to debug it

**Comment by ajthinking** [comment]
Suspect my build is producing bad output. So pushed it to github pages. See it there:

image

Can you confirm if you also get this error now when visiting github pages and pressing enter on a selected node?

**Comment by Lenivaya** [comment]
> Can you confirm if you also get this error now when visiting github pages and pressing enter on a selected node?
Yeah, I have the same error now

**Comment by Lenivaya** [comment]
It's really strange because build generated on my local machine and by github actions doesn't have such problems

**Pull request merged**
